#!/usr/bin/python
#
# Copyright 2012 SAS Institute
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import os
import sys

# if non-installed bigitr python module exists parallel to this script,
# make sure it is at the beginning of the PYTHONPATH so that it is not
# only findable but used in preference to any installed bigitr, so that
# when run out of a checkout, we're using the checkout modules.
bigitrDirectory = os.path.dirname(os.path.dirname(os.path.abspath(sys.argv[0])))
if os.path.exists('/'.join((bigitrDirectory, 'bigitr'))):
    sys.path[0:0] = [bigitrDirectory]

from bigitr import bigitrdaemon
bigitrdaemon.main(sys.argv)
